feat: add support for arrays as children
developit/jsxobj pull request #4
Opened 2022-01-21 18:18 UTC by theianjones

resolves #3 

![party](https://media3.giphy.com/media/AcfTF7tyikWyroP0x7/giphy.gif?cid=74e957438vnrh8dwpz9psmcn89v8qlnr0ctammt0v1natjos&rid=giphy.gif&ct=g)

2022-01-22 04:00 UTC, texastoland commented
@theianjones I liked your implementation too 👏🏼 Look for my review inline.

@developit 1 open question is how to represent an array with a single element. The only idea I had was fragments like `<>...</>`. But that would be a separate PR anyway.

2022-01-25 20:23 UTC, theianjones commented
@texastoland I dont see a review

2022-01-27 02:25 UTC, texastoland requested changes

2022-01-27 02:25 UTC, texastoland commented on src/index.js
> +		}		else {
Do you not have the Prettier extension installed? Make sure to add an `.editorconfig` to keep tabs (you mixed them throughout).

2022-01-27 02:25 UTC, texastoland commented on src/index.js
> +      }
I might not have thought of `flat` 🤩

```suggestion
		obj[name] = obj[name] ? [obj[name], child].flat() : child
```

2022-01-27 02:25 UTC, texastoland commented on test/index.js
> +        </plugins>
Unintentional whitespace changes hurt the diff.

2022-01-27 02:25 UTC, texastoland commented on test/arrayFixture.json
> +    ]
Readme needs updated too 👏🏼

2022-03-25 01:37 UTC, merged